PROJECT_DIR = r'C:\Users\Dan\PycharmProjects\CollectionsGenerator'
DEF_F_EXTENSION = [("csv file(*.csv)", "*.csv")]
COLL_MAX_SIZE = 5000
CMS_UPLOAD_F_HEADERS = ['sellerid', 'productid', 'stock']
EXPORT_F_PARTIAL = f'collection_*_filtered_items*.csv'
DOWNLOAD_WAIT_T = 60
UPLOAD_WAIT_T = 60
ITEMS_FAILED_LIMIT = 10
DOWNLOADS_DIR = r'C:\Users\Dan\Downloads'
UPLOADS_DIR = fr'{PROJECT_DIR}\demo\uploads'
CMS_COLL_COLUMNS = ['Seller ID', 'Product ID', 'Price', 'Old Price', 'ADO', 'Stock', 'Rating', 'Offshore Seller']
BANK_COLL_COLUMNS = ['seller_id', 'product_id', 'price', 'ado', 'discount', 'category_id', 'cluster', 'rating', 'seller_type']
